export const modalActions = {  
    SHOW_ADD_MODAL: 'SHOW_ADD_MODAL',
    HIDE_ADD_MODAL: 'HIDE_ADD_MODAL',
    SHOW_EDIT_MODAL: 'SHOW_EDIT_MODAL',
    HIDE_EDIT_MODAL: 'HIDE_EDIT_MODAL',
    SHOW_DELETE_MODAL: 'SHOW_DELETE_MODAL',
    HIDE_DELETE_MODAL: 'HIDE_DELETE_MODAL',
    SHOW_VIEW_MODAL: 'SHOW_VIEW_MODAL',
    HIDE_VIEW_MODAL: 'HIDE_VIEW_MODAL',
}

export const todoActions = {  
    ADD_NEW_TODO_REQUEST: 'ADD_NEW_TODO_REQUEST',
    ADD_NEW_TODO_REQUEST_SUCCESS: 'ADD_NEW_TODO_REQUEST_SUCCESS',
    ADD_NEW_TODO_REQUEST_FAILED: 'ADD_NEW_TODO_REQUEST_FAILED',

    FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAILED: 'FETCH_TODOS_FAILED',

    FETCH_TODO_REQUEST: 'FETCH_TODO_REQUEST',
    FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
    FETCH_TODO_FAILED: 'FETCH_TODO_FAILED',

    EDIT_TODO_REQUEST: 'EDIT_TODO_REQUEST',
    EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
    EDIT_TODO_FAILED: 'EDIT_TODO_FAILED',

    DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAILED: 'DELETE_TODO_FAILED',
}

